### ISSUE TITLE
Config events not working properly with stardust examples.

### ISSUE THREAD

**Issue by PetrosKataras** [PetrosKataras/stardust#2]
Mouse events arriving to `seq::detail::MasterConfig::handleEvent` are broken when running stardust examples. On single-window config no mouse events are being reported and on multi-window configs sometimes they are reported and sometimes not. This behavior is not present when running the seqPly example.  
Maybe @eile you have an idea on what could be the reason for this ?

**Comment by PetrosKataras** [comment]
If I change from WINDOW_POINTER_\* to CHANNEL_POINTER_\* in [processEvent](https://github.com/PetrosKataras/stardust/blob/5977c9a2416925dbe64b48318bc6fd1ee230b118/src/stardust/internal/renderer.cpp#L204-L284) of the renderer, events are being forward properly and everything works as expected.

**Comment by eile** [comment]
Yes, window events are translated into a channel event whenever a channel can be identified. This way you also have the associated render context.

**Comment by PetrosKataras** [comment]
So is this expected behavior and the solution is just to switch to CHANNEL_POINTER_\* ? This way you can't handle directly WINDOW_POINTER_\* events from Renderer::processEvent and maybe it should be documented .

**Comment by eile** [comment]
Yes, WINDOW_POINTER is just for unassigneable events. Will document.
